version: '3.9'
services:
  ruuter:
    container_name: node_2
    build:
      context: .
    ports:
      - 3000:3000
    networks:
      - bykstack

networks:
  bykstack:
    driver: bridge
#    external: true
